name: DAG - ACS_CONDITION PRE-CACHE INGESTION (PROD)

# NOTE: This workflow pre-caches ACS response into our GCS landing buckets; it does not need to be run every time unless the source data is expected to have changed.

on:
  workflow_dispatch:
jobs:
  call-staging-workflow:
    uses: SatcherInstitute/health-equity-tracker/.github/workflows/dagAcsConditionPreCache.yml@main
    secrets: inherit
