name: DAG - CDC_VACCINATION_COUNTY (PROD)
on:
  workflow_dispatch:
jobs:
  call-staging-workflow:
    uses: SatcherInstitute/health-equity-tracker/.github/workflows/dagCdcVaccinationCounty.yml@main
    secrets: inherit
