name: DEPLOY TO PROD ON RELEASE
on:
  # Auto triggered from health-equity-tracker release
  repository_dispatch:
    types: [release-triggered]
  # Manual trigger for controlled production deployments
  workflow_dispatch:
    inputs:
      release:
        description: "Release version to deploy"
        required: true

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Production Repository
        uses: actions/checkout@v4
        with:
          path: health-equity-tracker-prod

      - name: Checkout HET Repository
        uses: actions/checkout@v4
        with:
          repository: SatcherInstitute/health-equity-tracker
          ref: ${{ github.event.inputs.release || github.event.client_payload.release }}
          path: health-equity-tracker

      - name: Copy Production Config Files
        run: |
          # Copy production vars file to the HET repo
          cp health-equity-tracker-prod/config/gcp.tfvars health-equity-tracker/config/

      - name: Deploy to Production
        uses: SatcherInstitute/health-equity-tracker/.github/actions/buildAllAndDeploy@main
        with:
          ref: ${{ github.event.inputs.release || github.event.client_payload.release }}
          environment: prod
          deployer-sa-key: ${{ secrets.PROD_DEPLOYER_SA_KEY }}
          project-id: ${{ secrets.GCP_PROJECT_ID }}
          tf-state-bucket: het-prod-state
          ahr-api-key: 12345
