name: DEPLOY TO PROD ON RELEASE
on:
  # Auto triggered from health-equity-tracker release
  repository_dispatch:
    types: [release-triggered]
  # Manual trigger for rollbacks or troubleshooting
  workflow_dispatch:
    inputs:
      release:
        description: Release Version for Production
        required: true
jobs:
  deploy:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
        with:
          repository: SatcherInstitute/health-equity-tracker
          ref: ${{ github.event.client_payload.release || github.event.inputs.release }}
      - name: Deploy to Production
        uses: ./.github/actions/buildAllAndDeploy
        with:
          ref: ${{ github.event.client_payload.release || github.event.inputs.release }}
          environment: prod
          terraform-var-file: ../../main/config/prod.tfvars
          deployer-sa-key: ${{ secrets.PROD_DEPLOYER_SA_KEY }}
          project-id: ${{ secrets.GCP_PROJECT_ID }}
          tf-state-bucket: het-prod-state
          ahr-api-key: ${{ secrets.AHR_API_KEY }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
