name: AUTO-DEPLOY TO PROD ON HET RELEASE
on:
  # Auto triggered from health-equity-tracker release
  repository_dispatch:
    types: [release-triggered]
jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HET Repository
        uses: actions/checkout@v4
        with:
          repository: SatcherInstitute/health-equity-tracker
          ref: ${{ github.event.client_payload.release }}
      - name: Checkout Production Repository
        uses: actions/checkout@v4
        with:
          path: prod
      - name: Copy Production Config Files
        run: |
          # Copy production vars file to the HET repo
          cp prod/config/gcp.tfvars config/
      - name: Deploy to Production
        uses: SatcherInstitute/health-equity-tracker/.github/actions/buildAllAndDeploy@main
        with:
          ref: ${{ github.event.client_payload.release }}
          environment: prod
          deployer-sa-key: ${{ secrets.PROD_DEPLOYER_SA_KEY }}
          project-id: ${{ secrets.GCP_PROJECT_ID }}
          tf-state-bucket: het-prod-state
          ahr-api-key: TODO_MAKE_THIS_OPTIONAL
